import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { ThemeProvider } from "./_components/theme-provider";
import { ThemeToggle } from "./_components/theme-toggle";
import React from "react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${geist.variable}`}>
      <body>
        <ThemeProvider defaultTheme="system">
          <div className="flex min-h-screen flex-col">
            <header>
              <div className="container mx-auto flex h-16 items-center justify-between px-4">
                <div className="text-xl font-bold">Little Eleven</div>
                <ThemeToggle />
              </div>
            </header>
            <main className="container mx-auto flex-1 px-4 py-8">
              <TRPCReactProvider>{children}</TRPCReactProvider>
            </main>
            <footer className="bg-background border-t">
              <div className="container mx-auto px-4 py-6 text-center text-sm">
                © {new Date().getFullYear()} Little Eleven. All rights reserved.
              </div>
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
