/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */

export type AssetObjectUrlAllOf = {
  original: string;
  thumbnail_300_: string;
  thumbnail_700_: string;
  thumbnail_blur_: string;
  webp: string;
};
