/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */
import type { CosBucket } from './cosBucket';
import type { AssetExif } from './assetExif';
import type { AssetMetadata } from './assetMetadata';
import type { AssetObjectUrlAllOf } from './assetObjectUrlAllOf';
import type { AssetSizeAnyOf } from './assetSizeAnyOf';
import type { User } from './user';

export interface Asset {
  alt: string;
  bucket: CosBucket;
  comment: string;
  createdAt: string;
  exif: AssetExif;
  fileSuffix: string;
  id: number;
  metadata: AssetMetadata;
  objectUrl: AssetObjectUrlAllOf;
  originUrl: string;
  pHash: string;
  sha1: string;
  size: AssetSizeAnyOf;
  sn: string;
  tags: string[];
  updatedAt: string;
  uploadBy: User;
}
