/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */
import type { CosBucketACL } from './cosBucketACL';
import type { Asset } from './asset';
import type { CosBucketRefererConfiguration } from './cosBucketRefererConfiguration';
import type { TencentCloudAccount } from './tencentCloudAccount';

export interface CosBucket {
  ACL: CosBucketACL;
  assets: Asset[];
  Bucket: string;
  CORSRules: string[];
  createdAt: string;
  id: number;
  /** bucket 在系统中的名称 */
  name: string;
  public: boolean;
  RefererConfiguration: CosBucketRefererConfiguration;
  Region: string;
  tencentCloudAccount: TencentCloudAccount;
  updatedAt: string;
}
