/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */

export interface CreateMomentDto {
  content?: string;
  createdAt?: unknown;
  id?: number;
  type?: string;
  updatedAt?: unknown;
  uploadIds?: number[];
}
