/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */
import type { CreateEventDtoExtraFieldsItem } from './createEventDtoExtraFieldsItem';

export interface CreateEventDto {
  createdAt?: unknown;
  displayName: string;
  extraFields?: CreateEventDtoExtraFieldsItem[];
  icon: string;
  id?: number;
  name: string;
  updatedAt?: unknown;
}
