/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { EventLogPostRequestExtra } from './eventLogPostRequestExtra';

export interface EventLogPostRequest {
  comment?: string;
  eventName: string;
  eventTime?: string;
  extra?: EventLogPostRequestExtra;
}
