/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export type EventExtraFieldsItemType = typeof EventExtraFieldsItemType[keyof typeof EventExtraFieldsItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventExtraFieldsItemType = {
  text: 'text',
  number: 'number',
  time: 'time',
  radio: 'radio',
  checkbox: 'checkbox',
  picker: 'picker',
} as const;
