/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { EventLogExtra } from './eventLogExtra';

export interface EventLog {
  comment?: string;
  createdAt: string;
  eventName: string;
  eventTime?: string;
  extra?: EventLogExtra;
  id: number;
  updatedAt: string;
}
