/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { EventExtraFields } from './eventExtraFields';

export interface EventPatchRequest {
  displayName?: string;
  extraFields?: EventExtraFields;
  icon?: string;
  id: number;
  name?: string;
}
