/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { EventExtraFieldsItemCascade } from './eventExtraFieldsItemCascade';
import type { EventExtraFieldsItemType } from './eventExtraFieldsItemType';

export type EventExtraFieldsItem = {
  cascade?: EventExtraFieldsItemCascade;
  defaultValue?: string;
  displayName: string;
  enums?: string[];
  name: string;
  required?: boolean;
  type: EventExtraFieldsItemType;
  userInput?: boolean;
};
