/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { EventLogPatchRequestExtra } from './eventLogPatchRequestExtra';

export interface EventLogPatchRequest {
  comment?: string;
  eventTime?: string;
  extra?: EventLogPatchRequestExtra;
  id: number;
}
