/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */
import type { Asset } from './asset';
import type { User } from './user';

export interface Feed {
  assets: Asset[];
  content: string;
  createBy: User;
  createdAt: string;
  id: number;
  public: boolean;
  updateBy: User;
  updatedAt: string;
}
