/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBabyId200Avatar } from './getApiBabyId200Avatar';

export type GetApiBabyId200 = {
  avatar: GetApiBabyId200Avatar;
  bornAt: string;
  gender: number;
  name: string;
};
