/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMoment200DataItem } from './getApiMoment200DataItem';

export type GetApiMoment200 = {
  data: GetApiMoment200DataItem[];
  total: number;
};
