/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMoment200DataItemAttachmentsItemBucket } from './getApiMoment200DataItemAttachmentsItemBucket';

export type GetApiMoment200DataItemAttachmentsItem = {
  bucket: GetApiMoment200DataItemAttachmentsItemBucket;
  bucketName: string;
  createdAt: string;
  hash: string;
  id: number;
  mediaType: string;
  thumbnailHash: string;
  updatedAt: string;
};
