/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiMoment200DataItemType = typeof GetApiMoment200DataItemType[keyof typeof GetApiMoment200DataItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiMoment200DataItemType = {
  moment: 'moment',
  feedback: 'feedback',
} as const;
