/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBabyId200AvatarBucket } from './getApiBabyId200AvatarBucket';

export type GetApiBabyId200Avatar = {
  bucket: GetApiBabyId200AvatarBucket;
  bucketName: string;
  createdAt: string;
  hash: string;
  id: number;
  mediaType: string;
  thumbnailHash: string;
  updatedAt: string;
};
