/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */
import type { InfiniteQueryResponse } from './infiniteQueryResponse';
import type { InfiniteQueryPublicTimeline200AllOf } from './infiniteQueryPublicTimeline200AllOf';

export type InfiniteQueryPublicTimeline200 = InfiniteQueryResponse & InfiniteQueryPublicTimeline200AllOf;
