/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */
import type { InfiniteQueryResponse } from './infiniteQueryResponse';
import type { InfiniteQueryPublicAsset200AllOf } from './infiniteQueryPublicAsset200AllOf';

export type InfiniteQueryPublicAsset200 = InfiniteQueryResponse & InfiniteQueryPublicAsset200AllOf;
