/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */
import type { InfiniteQueryResponse } from './infiniteQueryResponse';
import type { InfiniteQueryPublicPost200AllOf } from './infiniteQueryPublicPost200AllOf';

export type InfiniteQueryPublicPost200 = InfiniteQueryResponse & InfiniteQueryPublicPost200AllOf;
