/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */
import type { MenuChildren } from './menuChildren';
import type { MenuParent } from './menuParent';

export interface Menu {
  children: MenuChildren;
  createdAt: string;
  id: number;
  name: string;
  parent: MenuParent;
  parentId: number | null;
  path: string;
  updatedAt: string;
}
