/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export type MomentPostRequestType = typeof MomentPostRequestType[keyof typeof MomentPostRequestType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MomentPostRequestType = {
  moment: 'moment',
  feedback: 'feedback',
} as const;
