/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { MomentPostRequestAttachmentsItem } from './momentPostRequestAttachmentsItem';
import type { MomentPostRequestType } from './momentPostRequestType';

export interface MomentPostRequest {
  attachments?: MomentPostRequestAttachmentsItem[];
  content: string;
  type?: MomentPostRequestType;
}
