/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { MomentPutRequestAttachmentsItem } from './momentPutRequestAttachmentsItem';

export interface MomentPutRequest {
  attachments?: MomentPutRequestAttachmentsItem[];
  content: string;
  id: number;
}
