/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */

export type OauthApplicationPlatformName = typeof OauthApplicationPlatformName[keyof typeof OauthApplicationPlatformName];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OauthApplicationPlatformName = {
  google: 'google',
  github: 'github',
  test: 'test',
} as const;
