/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */
import type { OauthApplication } from './oauthApplication';
import type { User } from './user';

export interface OauthOpenid {
  application: OauthApplication;
  createdAt: string;
  id: number;
  openid: string;
  updatedAt: string;
  user: User;
}
