/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiUpload200Bucket = {
  createdAt: string;
  domain: string;
  id: number;
  name: string;
  updatedAt: string;
};
