/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiHelloGeminiProBodyContentsItemPartsItem } from './postApiHelloGeminiProBodyContentsItemPartsItem';

export type PostApiHelloGeminiProBodyContentsItem = {
  parts: PostApiHelloGeminiProBodyContentsItemPartsItem[];
};
