/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiMoment200Type = typeof PostApiMoment200Type[keyof typeof PostApiMoment200Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiMoment200Type = {
  moment: 'moment',
  feedback: 'feedback',
} as const;
