/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiMoment200AttachmentsItemBucket } from './postApiMoment200AttachmentsItemBucket';

export type PostApiMoment200AttachmentsItem = {
  bucket: PostApiMoment200AttachmentsItemBucket;
  bucketName: string;
  createdAt: string;
  hash: string;
  id: number;
  mediaType: string;
  thumbnailHash: string;
  updatedAt: string;
};
