/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { EventPostRequest } from './eventPostRequest';

export type PostApiEventBody = EventPostRequest[] | EventPostRequest;
