/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiMoment200AttachmentsItem } from './postApiMoment200AttachmentsItem';
import type { PostApiMoment200Type } from './postApiMoment200Type';

export type PostApiMoment200 = {
  attachments: PostApiMoment200AttachmentsItem[];
  content: string;
  createdAt: string;
  id: number;
  type?: PostApiMoment200Type;
  updatedAt: string;
};
