/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */
import type { PushSubscriptionJSONDtoKeys } from './pushSubscriptionJSONDtoKeys';

export interface PushSubscriptionJSONDto {
  endpoint?: string;
  expirationTime?: number | null;
  keys?: PushSubscriptionJSONDtoKeys;
}
