/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiMoment200AttachmentsItemBucket } from './putApiMoment200AttachmentsItemBucket';

export type PutApiMoment200AttachmentsItem = {
  bucket: PutApiMoment200AttachmentsItemBucket;
  bucketName: string;
  createdAt: string;
  hash: string;
  id: number;
  mediaType: string;
  thumbnailHash: string;
  updatedAt: string;
};
