/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiMoment200AttachmentsItem } from './putApiMoment200AttachmentsItem';
import type { PutApiMoment200Type } from './putApiMoment200Type';

export type PutApiMoment200 = {
  attachments: PutApiMoment200AttachmentsItem[];
  content: string;
  createdAt: string;
  id: number;
  type?: PutApiMoment200Type;
  updatedAt: string;
};
