/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export type PutApiMoment200Type = typeof PutApiMoment200Type[keyof typeof PutApiMoment200Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiMoment200Type = {
  moment: 'moment',
  feedback: 'feedback',
} as const;
