/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */

export interface QueryRequestLogDto {
  contentLength: string;
  /** 创建时间 */
  createdAt: string[];
  /** 当前页码 */
  current: number;
  id: number;
  ip: string;
  ipInfo: string;
  method: string;
  /** 每页条数 */
  pageSize: number;
  path: string;
  processTime: string;
  referer: string;
  requestId: string;
  statusCode: number;
  /** 更新时间 */
  updatedAt: string[];
  userAgent: string;
}
