/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */

export type QueryUsersParams = {
/**
 * 每页条数
 */
pageSize: number;
/**
 * 当前页码
 */
current: number;
/**
 * User id
 */
id: number;
/**
 * User email
 */
email: string;
nickname: string;
bio: string;
/**
 * 创建时间
 */
createdAt?: string[];
/**
 * 更新时间
 */
updatedAt?: string[];
};
