/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */

export type QueryRolesParams = {
/**
 * 每页条数
 */
pageSize: number;
/**
 * 当前页码
 */
current: number;
id: number;
name: string;
createdAt?: string[];
updatedAt?: string[];
};
