/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';
import type { Asset } from './asset';

export interface QueryPostsDto {
  content: string;
  createBy: User;
  /** 创建时间 */
  createdAt: string[];
  /** 当前页码 */
  current: number;
  id: number;
  /** 每页条数 */
  pageSize: number;
  poster: Asset;
  public: boolean;
  summary: string;
  title: string;
  /** 更新时间 */
  updatedAt: string[];
}
