/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */

export interface RequestLog {
  contentLength: string;
  createdAt: string;
  id: number;
  ip: string;
  ipInfo: string;
  method: string;
  path: string;
  processTime: string;
  referer: string;
  requestId: string;
  statusCode: number;
  updatedAt: string;
  userAgent: string;
}
