/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */
import type { Menu } from './menu';

export interface Role {
  createdAt: string;
  id: number;
  /** 菜单列表 */
  menus: Menu[];
  name: string;
  /** 权限列表 */
  permissions: string[];
  updatedAt: string;
}
