/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */
import type { UpdateEventLogDtoExtra } from './updateEventLogDtoExtra';

export interface UpdateEventLogDto {
  comment?: string;
  createdAt?: unknown;
  eventName: string;
  eventTime?: unknown;
  extra?: UpdateEventLogDtoExtra;
  updatedAt?: unknown;
}
