/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Backend API
 * The API is used for powerfulyang.com
 * OpenAPI spec version: 1.0
 */
import type { Family } from './family';
import type { OauthOpenid } from './oauthOpenid';
import type { Role } from './role';
import type { Asset } from './asset';

export interface User {
  avatar?: string;
  bio: string;
  createdAt: string;
  /** User email */
  email: string;
  families: Family[];
  /** User id */
  id: number;
  lastAddress: string;
  lastIp: string;
  nickname: string;
  oauthOpenidArr: OauthOpenid[];
  /** User roles */
  roles: Role[];
  salt: string;
  saltedPassword: string;
  timelineBackground: Asset;
  updatedAt: string;
}
