/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query'
import {
  unref
} from 'vue'
import type {
  MaybeRef
} from 'vue'
import type {
  DeleteApiEventLogId200,
  Event,
  EventLog,
  EventLogDistinctResult,
  EventLogPatchRequest,
  EventLogPostRequest,
  EventLogResult,
  EventPatchRequest,
  GetApiEventLogDistinctParams,
  GetApiEventLogParams,
  InternalServerError,
  PostApiEventBody
} from '../model'
import { customInstance } from '../../api/mutator/custom-instance';
import type { ErrorType } from '../../api/mutator/custom-instance';



export const postApiEvent = (
    postApiEventBody: MaybeRef<PostApiEventBody>,
 ) => {
      postApiEventBody = unref(postApiEventBody);
      
      return customInstance<Event[]>(
      {url: `/api/event`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiEventBody
    },
      );
    }
  


export const getPostApiEventMutationOptions = <TError = ErrorType<InternalServerError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiEvent>>, TError,{data: PostApiEventBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiEvent>>, TError,{data: PostApiEventBody}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiEvent>>, {data: PostApiEventBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiEvent(data,)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type PostApiEventMutationResult = NonNullable<Awaited<ReturnType<typeof postApiEvent>>>
    export type PostApiEventMutationBody = PostApiEventBody
    export type PostApiEventMutationError = ErrorType<InternalServerError>

    export const usePostApiEvent = <TError = ErrorType<InternalServerError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiEvent>>, TError,{data: PostApiEventBody}, TContext>, }
) => {

      const mutationOptions = getPostApiEventMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const getApiEvent = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<Event[]>(
      {url: `/api/event`, method: 'GET', signal
    },
      );
    }
  

export const getGetApiEventQueryKey = () => {
    return ['api','event'] as const;
    }

    
export const getGetApiEventQueryOptions = <TData = Awaited<ReturnType<typeof getApiEvent>>, TError = ErrorType<InternalServerError>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEvent>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  getGetApiEventQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiEvent>>> = ({ signal }) => getApiEvent(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiEvent>>, TError, TData> 
}

export type GetApiEventQueryResult = NonNullable<Awaited<ReturnType<typeof getApiEvent>>>
export type GetApiEventQueryError = ErrorType<InternalServerError>

export const useGetApiEvent = <TData = Awaited<ReturnType<typeof getApiEvent>>, TError = ErrorType<InternalServerError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEvent>>, TError, TData>>, }

  ): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiEventQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey as QueryKey;

  return query;
}




export const patchApiEvent = (
    eventPatchRequest: MaybeRef<EventPatchRequest>,
 ) => {
      eventPatchRequest = unref(eventPatchRequest);
      
      return customInstance<Event>(
      {url: `/api/event`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: eventPatchRequest
    },
      );
    }
  


export const getPatchApiEventMutationOptions = <TError = ErrorType<InternalServerError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiEvent>>, TError,{data: EventPatchRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiEvent>>, TError,{data: EventPatchRequest}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiEvent>>, {data: EventPatchRequest}> = (props) => {
          const {data} = props ?? {};

          return  patchApiEvent(data,)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type PatchApiEventMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiEvent>>>
    export type PatchApiEventMutationBody = EventPatchRequest
    export type PatchApiEventMutationError = ErrorType<InternalServerError>

    export const usePatchApiEvent = <TError = ErrorType<InternalServerError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiEvent>>, TError,{data: EventPatchRequest}, TContext>, }
) => {

      const mutationOptions = getPatchApiEventMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const postApiEventLog = (
    eventLogPostRequest: MaybeRef<EventLogPostRequest>,
 ) => {
      eventLogPostRequest = unref(eventLogPostRequest);
      
      return customInstance<EventLog>(
      {url: `/api/event-log`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: eventLogPostRequest
    },
      );
    }
  


export const getPostApiEventLogMutationOptions = <TError = ErrorType<InternalServerError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiEventLog>>, TError,{data: EventLogPostRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiEventLog>>, TError,{data: EventLogPostRequest}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiEventLog>>, {data: EventLogPostRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiEventLog(data,)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type PostApiEventLogMutationResult = NonNullable<Awaited<ReturnType<typeof postApiEventLog>>>
    export type PostApiEventLogMutationBody = EventLogPostRequest
    export type PostApiEventLogMutationError = ErrorType<InternalServerError>

    export const usePostApiEventLog = <TError = ErrorType<InternalServerError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiEventLog>>, TError,{data: EventLogPostRequest}, TContext>, }
) => {

      const mutationOptions = getPostApiEventLogMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const getApiEventLog = (
    params?: MaybeRef<GetApiEventLogParams>,
 signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<EventLogResult[]>(
      {url: `/api/event-log`, method: 'GET',
        params: unref(params), signal
    },
      );
    }
  

export const getGetApiEventLogQueryKey = (params?: MaybeRef<GetApiEventLogParams>,) => {
    return ['api','event-log', ...(params ? [params]: [])] as const;
    }

    
export const getGetApiEventLogQueryOptions = <TData = Awaited<ReturnType<typeof getApiEventLog>>, TError = ErrorType<InternalServerError>>(params?: MaybeRef<GetApiEventLogParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEventLog>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  getGetApiEventLogQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiEventLog>>> = ({ signal }) => getApiEventLog(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiEventLog>>, TError, TData> 
}

export type GetApiEventLogQueryResult = NonNullable<Awaited<ReturnType<typeof getApiEventLog>>>
export type GetApiEventLogQueryError = ErrorType<InternalServerError>

export const useGetApiEventLog = <TData = Awaited<ReturnType<typeof getApiEventLog>>, TError = ErrorType<InternalServerError>>(
 params?: MaybeRef<GetApiEventLogParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEventLog>>, TError, TData>>, }

  ): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiEventLogQueryOptions(params,options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey as QueryKey;

  return query;
}




export const patchApiEventLog = (
    eventLogPatchRequest: MaybeRef<EventLogPatchRequest>,
 ) => {
      eventLogPatchRequest = unref(eventLogPatchRequest);
      
      return customInstance<EventLog>(
      {url: `/api/event-log`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: eventLogPatchRequest
    },
      );
    }
  


export const getPatchApiEventLogMutationOptions = <TError = ErrorType<InternalServerError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiEventLog>>, TError,{data: EventLogPatchRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiEventLog>>, TError,{data: EventLogPatchRequest}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiEventLog>>, {data: EventLogPatchRequest}> = (props) => {
          const {data} = props ?? {};

          return  patchApiEventLog(data,)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type PatchApiEventLogMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiEventLog>>>
    export type PatchApiEventLogMutationBody = EventLogPatchRequest
    export type PatchApiEventLogMutationError = ErrorType<InternalServerError>

    export const usePatchApiEventLog = <TError = ErrorType<InternalServerError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiEventLog>>, TError,{data: EventLogPatchRequest}, TContext>, }
) => {

      const mutationOptions = getPatchApiEventLogMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const getApiEventLogDistinct = (
    params?: MaybeRef<GetApiEventLogDistinctParams>,
 signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<EventLogDistinctResult[]>(
      {url: `/api/event-log/distinct`, method: 'GET',
        params: unref(params), signal
    },
      );
    }
  

export const getGetApiEventLogDistinctQueryKey = (params?: MaybeRef<GetApiEventLogDistinctParams>,) => {
    return ['api','event-log','distinct', ...(params ? [params]: [])] as const;
    }

    
export const getGetApiEventLogDistinctQueryOptions = <TData = Awaited<ReturnType<typeof getApiEventLogDistinct>>, TError = ErrorType<InternalServerError>>(params?: MaybeRef<GetApiEventLogDistinctParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEventLogDistinct>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  getGetApiEventLogDistinctQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiEventLogDistinct>>> = ({ signal }) => getApiEventLogDistinct(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiEventLogDistinct>>, TError, TData> 
}

export type GetApiEventLogDistinctQueryResult = NonNullable<Awaited<ReturnType<typeof getApiEventLogDistinct>>>
export type GetApiEventLogDistinctQueryError = ErrorType<InternalServerError>

export const useGetApiEventLogDistinct = <TData = Awaited<ReturnType<typeof getApiEventLogDistinct>>, TError = ErrorType<InternalServerError>>(
 params?: MaybeRef<GetApiEventLogDistinctParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEventLogDistinct>>, TError, TData>>, }

  ): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiEventLogDistinctQueryOptions(params,options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey as QueryKey;

  return query;
}




export const deleteApiEventLogId = (
    id: MaybeRef<string>,
 ) => {
      id = unref(id);
      
      return customInstance<DeleteApiEventLogId200>(
      {url: `/api/event-log/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiEventLogIdMutationOptions = <TError = ErrorType<InternalServerError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiEventLogId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiEventLogId>>, TError,{id: string}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiEventLogId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiEventLogId(id,)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type DeleteApiEventLogIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiEventLogId>>>
    
    export type DeleteApiEventLogIdMutationError = ErrorType<InternalServerError>

    export const useDeleteApiEventLogId = <TError = ErrorType<InternalServerError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiEventLogId>>, TError,{id: string}, TContext>, }
) => {

      const mutationOptions = getDeleteApiEventLogIdMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
